### PR TITLE
fix cookies import when create the websocket

### PR DESCRIPTION
**Pull request by hschouman**
The upgrade to web socket should import only cookies relative to the url.
Without this specify, all cookies are imported and in my case it never upgrade to web socket (because there are several cookies in header that does not match the session)

### CODE REVIEW

**Comment by hschouman** [comment]
For more information on my use case with cookies here, I use session affinity on heroku :
https://devcenter.heroku.com/articles/session-affinity

But I guess there are other use cases with cookies here

**Comment by nuclearace** [comment]
Hm, the idea for this was to allow cookies from the initial polling connection to carry over to the websocket connection.

**Comment by leuducquy** [comment]
Merge

**Comment by nuclearace** [comment]
@hschouman Have you tested if this ever actually returns cookies? There's a scheme difference between `urlWebSocketWithSid` and `urlPollingWithSid`, and session will only ever have the polling url.

**Comment by hschouman** [comment]
You are right. In my case I have the same result with the two schemes because the cookies are stored with the base url (path == "/").
I've just fixed that.

**Comment by nuclearace** [comment]
@hschouman One last thing, can you change this to be opened against development?

**Comment by OneSman7** [comment]
Found this after made comment in my PR #1058 (https://github.com/socketio/socket.io-client-swift/pull/1058#issuecomment-425062388).
This PR also fixes bug described there. It is only left to decide whether it will be better to pass filtered cookies to _addHeaders_ method or to filter them by domain inside _addHeaders_ method.

**Pull request merged**
