### PR TITLE
Propagate websocket connected event to SocketIOClientStatus when forced websocket connection

### PR DESCRIPTION
**Pull request by therudite**

### CODE REVIEW

**Comment by nuclearace** [comment]
Shouldn't the open packet be sent over WebSocket anyway?

**Comment by therudite** [comment]
Yes, it is sending and websocket is connected as well but this is not getting reflected in socket status.

**Comment by nuclearace** [comment]
Right, but is a connect event being emitted when forcing websocket? Because the websocket methods shouldn't be sending events to the client directly, they should come through the websocket and be sent the handle method.

**Comment by nuclearace** [comment]
https://github.com/socketio/socket.io-client-swift/blob/development/Source/SocketIOClient.swift#L188

https://github.com/socketio/socket.io-client-swift/blob/development/Source/SocketParsable.swift#L39

**Pull request closed without merging**
