### PR TITLE
Fix secure option issue

### PR DESCRIPTION
**Pull request by brightsider**

### CODE REVIEW

**Comment by nuclearace** [comment]
Is this an issue though? Specifying https should be enough

**Comment by brightsider** [comment]
Then why options contains secure if this doesn't use?

**Comment by nuclearace** [comment]
I don't see `secure` listed on the README for options

**Comment by brightsider** [comment]
It was previously in the README, and there were no instructions for migration. May be worth add in the README that the need to specify the address with https?

**Comment by nuclearace** [comment]
I'll add something to the README

**Pull request closed without merging**
