### PR TITLE
Add CocoaPods podspec

### PR DESCRIPTION
**Pull request by banjun**
refs #2 

I have added a podspec and a example project, although there are some difficulty because SocketRocket's current commits are not published to the master CocoaPods/Specs repo...
please edit the URLs, authors and tags in the podspec file and LICENSE file (stub).

### CODE REVIEW

**Comment by nuclearace** [comment]
I'm actually in the process of moving to starscream per #3.

**Comment by nuclearace** [comment]
Also, using CocoaPods would mean iOS 8+ only, and I'm not sure if I want to do that right now.

**Comment by Katafalkas** [comment]
How come ? Do you have a link to that information ? Cant seem to find it.

**Comment by nuclearace** [comment]
http://blog.cocoapods.org/CocoaPods-0.36/

**Comment by nuclearace** [comment]
Basically you can't have dynamic libraries in iOS 7. And you can't build static Swift libraries.

**Comment by banjun** [comment]
Yes, CocoaPods does not support Swift pods on iOS 7.
While theoretically we can make a swift library hybrid for both as a submodule and as a pod, I understand that it may need some more work to maintain.

Anyway, I rebased on Starscream commits. this should work with both CocoaPods and submodule.
https://github.com/banjun/socket.io-client-swift/tree/cocoapods-starscream

I think this PR 4 may be closed because this conflicts with the current master.

**Comment by nuclearace** [comment]
@banjun if you want to open another that will merge. I don't have time to manually sort out conflicts.

**Comment by nuclearace** [comment]
Also, you don't really need to include an example. One is linked in the README

**Comment by banjun** [comment]
I'll rebase and open another one without the example. Thanks!

**Pull request closed without merging**
