### PR TITLE
Test refactors

### PR DESCRIPTION
**Pull request by nuclearace**
- Moves back to xctool
- Separates the namespace socket from the regular socket. This will better expose issues in namespaces

### CODE REVIEW

**Comment by nuclearace** [comment]
Ugh, I think I introduced that old test bug where sometimes the tests randomly fail.

**Comment by nuclearace** [comment]
Probably the same problem we had before. But I think we need multiple sockets to test namespaces and polling stuff.

**Comment by nuclearace** [comment]
@lightsprint09 do you have any suggestions with this? I'd like to try and separate the sockets based on what they're testing. But having 4 different sockets seems to be causing travis problems.

**Comment by lightsprint09** [comment]
I didn't have time to take a look at it. Hopefully I find some time tomorrow

**Comment by lightsprint09** [comment]
I would not kill the old tests
They are as important as the new ones

**Comment by nuclearace** [comment]
Going to go ahead and merge this and continuously work on adding more tests

**Comment by lightsprint09** [comment]
did you remove all the old tests

**Comment by nuclearace** [comment]
Yeah, moving forward it'll be done more with mocking. Eventually I'm going to add some tests for the transport upgrading and connecting to namespaces. But the parsing stuff will mock tested. The client tests are pretty easy to mock out. But I think I'm going to need to refactor the engine to make easier to do testing on.

**Pull request merged**
