### PR TITLE
v16.1.1

### PR DESCRIPTION
**Pull request by nuclearace**
Fixes for various connection status stuff

### CODE REVIEW

**Comment by nuclearace** [comment]
@WestFlow127 LMK how testing goes

**Comment by WestFlow127** [comment]
> @WestFlow127 LMK how testing goes

@nuclearace , I pulled the repo, switch to this PR, and ran all tests in `TestSocketIO` and all passed!
Is there anything else you'd like me to do?

**Comment by nuclearace** [comment]
@WestFlow127, if you're able, testing against a socket.io server and doing some basic sanity checks would be helpful

**Comment by WestFlow127** [comment]
@nuclearace I can do that, we run a socket.io server at my company. I'll test general functionality, various reconnection scenarios, and the timingOut fix.

**Comment by WestFlow127** [comment]
### **Update:**
Was able to test general functionality which was good. Testing various reconnects was difficult due to my locations poor 5G service. I want to test on stable/good connections. Will likely do so over the holiday. (@nuclearace )

**Comment by mahyarq** [comment]
I can see that this version fixes the issue i just reported on #1470 
Need any help with getting anything done to prepare this for release? @nuclearace @WestFlow127

**Comment by miguelaboliveira** [comment]
Any ETA for this release?

**Comment by WestFlow127** [comment]
I have the green light to resume testing this PR during my workday tomorrow.
Going to further test socket reconnects using cellular service with our live socket server.
Stay tuned @nuclearace

**Comment by WestFlow127** [comment]
Just finished testing 5G/cellular reconnects and it worked great. 
Immediately reconnected to socket upon 5G reconnection.
I believe this PR is good to go, @nuclearace

**Comment by WestFlow127** [comment]
More users of this repo are requesting this to be merged: https://github.com/socketio/socket.io-client-swift/pull/1375#issuecomment-1919443113

@nuclearace I support merging this as I have tested it against our socket server.

**Comment by xmollv** [comment]
> More users of this repo are requesting this to be merged: [#1375 (comment)](https://github.com/socketio/socket.io-client-swift/pull/1375#issuecomment-1919443113)
> 
> @nuclearace I support merging this as I have tested it against our socket server.

Can we get it in? Would solve a big issue we're facing! 🙏🏼  // @nuclearace

**Comment by WestFlow127** [comment]
@nuclearace Please read above comments 🙏🏼

**Comment by Crysis21** [comment]
@nuclearace any updates on the socket.io for swift? This library feels deprecated and it's the only package I've come accross in the socket.io ecosystem that is no longer maintained/working properly.

**Comment by xmollv** [comment]
> @nuclearace any updates on the socket.io for swift? This library feels deprecated and it's the only package I've come accross in the socket.io ecosystem that is no longer maintained/working properly.

We have the same question. Both on the server and on Android everything seems to work fine, but on iOS we're constantly battling issues due to the unreliability of this SDK. This PR made it somewhat better, but still seems that there's a ton of room for improvement - yet there doesn't seem to be any active development.

**Comment by Crysis21** [comment]
for us and many other people, the swift client doesn't connect in WS mode, only in polling. using latest nodeJS backend and android works flawless. sadly this is not the case with swift.

**Comment by nuclearace** [comment]
> for us and many other people, the swift client doesn't connect in WS mode, only in polling. using latest nodeJS backend and android works flawless. sadly this is not the case with swift.

Looking into this now

**Comment by WestFlow127** [comment]
@nuclearace Things to add to this version:
- Updated Privacy Manifest
- Update Starscream to v4.0.8

**Comment by neobie** [comment]
when is this v16.1.1 going to release ?

**Comment by DrunkardSworder** [comment]
Due to issues with Apple's review process, I had to upgrade from 15.x to 16.x recently. During previous tests on 16.x, I encountered various connection status problems, including but not limited to obtaining incorrect statuses. I hope 16.1.1 can be released as soon as possible. I suspect there are many others in a similar situation. Thank you very much for your attention to this matter.

**Comment by xmollv** [comment]
Can we all agree this SDK is no longer maintained? I've been thinking about building my own because of how terrible the experience for our users is, but before I embark in such a quest, I'd like to know for sure if there's any plan to solve the plethora of connection issues that we're all experiencing or not.

**Comment by DjalilovGusein** [comment]
Please, fix the issue with reconnection

**Pull request merged**
