### PR TITLE
swift compile time optimizations

### PR DESCRIPTION
**Pull request by eventomer**
reducing about 20 seconds of compilation time because of swift type checker string concatenation issue

### CODE REVIEW

**Comment by nuclearace** [comment]
What, I've never seen it take more than 7 or 8 seconds to compile.

**Comment by nuclearace** [comment]
Also, you'll want to branch off of development and make changes there.

**Comment by MeGaPk** [comment]
@nuclearace you are lucky... I have 20-30 seconds... on my macbook pro.

**Comment by nuclearace** [comment]
Going to close this, since compile time should be a Swift issue itself.

**Comment by hfossli** [comment]
If this helps reducing 20 seconds of compilation now and the code is not suffering readability then I don't understand why it can't be merged. When is the "free string compilation time lunch" coming?

**Pull request closed without merging**
