### PR TITLE
[new feature] fix utf8 encoding

### PR DESCRIPTION
**Pull request by TomZid**
[new feature] fix utf8 encoding

### CODE REVIEW

**Comment by nuclearace** [comment]
What is this? There shouldn’t be anything wrong with Unicode if you’re using the right version of socket.io (2.0). If you’re trying to use 1.0 and the current version then it’ll be broken yes. Also, there’s a reason this library has Swift in the title. It should be written in swift, not objective c

**Comment by TomZid** [comment]
I used the version of v12.0.0.I found the problem of wrong decoding, that is, Chinese sent through longpolling can not be parsed correctly. After further analysis found that utf8 can not be resolved correctly. I compared the java version of the code, it is found that the swift version is less fault-tolerant, So I wrote the code following the java code.
The following address is Java's processing code: https://github.com/socketio/engine.io-client-java/blob/master/src/main/java/io/socket/utf8/UTF8.java

On 12/03/2017 20:46, Erik Little wrote: What is this? There shouldn’t be anything wrong with Unicode if you’re using the right version of socket.io (2.0). If you’re trying to use 1.0 and the current version then it’ll be broken yes. Also, there’s a reason this library has Swift in the title. It should be written in swift, not objective c

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/socketio/socket.io-client-swift","title":"socketio/socket.io-client-swift","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/socketio/socket.io-client-swift"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nuclearace in #893: What is this? There shouldn’t be anything wrong with Unicode if you’re using the right version of socket.io (2.0). If you’re trying to use 1.0 and the current version then it’ll be broken yes. Also, there’s a reason this library has Swift in the title. It should be written in swift, not objective c "}],"action":{"name":"View Pull Request","url":"https://github.com/socketio/socket.io-client-swift/pull/893#issuecomment-348763767"}}}

**Comment by nuclearace** [comment]
If that’s the case and the server is using 2.0, then this still should be written in Swift before I can be merged.

**Comment by nuclearace** [comment]
Also if you could provide a server/message example that causes the issue

**Comment by nuclearace** [comment]
Does it happen for all Chinese characters or only certain strings?

**Comment by TomZid** [comment]
It seems to happen for all Chinese words which is send by polling, like the following which is decoded by utf8  

1:61288:42/im/user,["message",{"nickName":"å°å","message":"{\"questions\":[{\"questionId\":\"5820160000078895\",\"question\":\"åæ¬¾æç°æ¶é´\"},{\"questionId\":\"5820160000078896\",\"question\":\"åæ¬¾å°è´¦æ¶é´\"},{\"questionId\":\"5820160000078897\",\"question\":\"åæ¬æ¬\302¾å®¡æ ¸æ¶é´\"},{\"questionId\":\"5820160000078887\",\"question\":\"èªå¨æç°å°ä¿¡ç¨å¡è¿æ¯é¶è¡è¿æ¯é¶è\302¡¡è¿æ¯é¶è\302¡\302¡è¿æ¯é¶è\302¡\302\303å¡ï¼åè®°å¡ï¼\"},{\"questionId\":\"5820160000078885\",\"question\":\"æ¾ç¤ºæååæ¬¾äºï¼æä¹åèªå¨æ¾å¼äº\"},{\"questionId\":\"5820160000078937\",\"question\":\"æä¹è§£ç»ä¿¡ç¨å¡/é¶è¡å¡\"},{\"questionId\":\"5820160000078938\",\"question\":\"ç»å®é¶è¡å¡æ¶ç³»ç»å¼å¸¸/ç³»ç»ç¹å¿\"},{\"questionId\":\"5820160000078923\",\"question\":\"è¿æ¬¾æ æ³æäº¤/ç³»ç»æ\302ç¤ºéè¯¯æç¹ç¹\303å¿\"},{\"questionId\":\"5820160000078924\",\"question\":\"é¾æè¿æ¬¾æ¯å¦ä¼æé¾æè®°å½åç½æ¯\"},{\"questionId\":\"5820160000078925\",\"question\":\"å·²ç»æ£æ¬¾ä¸ºä»ä¹è¿æ¾¹è¿æ¾\303ç¤ºææ¬ æ¬¾\"}],\"answer\":null,\"promptMsg\":\"æ¬¢è¿åä¸´ä½ æè´·ï¼å¾é«å´ä¸ºæ¨æå¡ï¼å°åçæ¨çé®é¢å¯è½æ¯:\"}","filesize":0,"fromUser":

**Comment by nuclearace** [comment]
I will double check, but last time I tested sending Unicode/Chinese characters in socket.io 2.0 I didn’t see any issues.

**Comment by TomZid** [comment]
The messages send by websocket is ok,the problem is the ones send by polling.I do not know the reason of it,but i have been confirmd from the backend that the encoding of pooling and websocket is the same.

**Comment by nuclearace** [comment]
@TomZid Are you doing something with the encoding before sending it on the serverside? I've been testing this locally using various unicode strings and I haven't seen any issue with the client decoding polling messages.

**Comment by nuclearace** [comment]
Also what server version are you using?

**Comment by TomZid** [comment]
I am not sure about the server side,tommorow I will give the answer

**Comment by TomZid** [comment]
Yet I have fixed this issue by my previous code,and sure it does work.I am not sure if it is caused by our misusing the API or something else.I appreciate you rapidly reply.

**Comment by jaykon** [comment]
the same problem,
client 15.0.0 with server 1.0+
but @TomZid code is work for me
thank you!

**Comment by TomZid** [comment]
@jaykon glad to hear that

**Pull request closed without merging**
