### PR TITLE
CocoaPods podspec for v1.1.0

### PR DESCRIPTION
**Pull request by banjun**
refs #2 #4

added a CocoaPods podspec file pointing to v1.1.0 and LICENSE file. (LICENSE file is required for pod validation.)

You can publish this pod after merge, according to the guide:
http://guides.cocoapods.org/making/getting-setup-with-trunk.html

1. signing up: `pod trunk register YOU@example.com 'YOUR NAME' --description='macbook air'`
2. sending to the Specs repo: `pod trunk push Socket.IO-Client-Swift.podspec`

### CODE REVIEW

**Comment by banjun** [comment]
`pod trunk push` validation may fail with this podspec like below..., as v1.1.0 tag does not contain LICENSE file.

```
 -> Socket.IO-Client-Swift (1.1.0)
    - WARN  | [iOS] Unable to find a license file
```

in the case, please tag after the merge commit and modify podspec's s.source line.
for example, `:tag => 'v1.1.0'` -> `:tag => 'v1.1.0-pod'`

**Comment by nuclearace** [comment]
@banjun I think I did it. But I have no idea.

**Comment by banjun** [comment]
@nuclearace thank you for merging! :+1: 

I confirmed we can now `pod search socket.io`, pod install with `pod 'Socket.IO-Client-Swift'`, and add `s.dependency 'Socket.IO-Client-Swift', '~> 1.1'` to another pod!

**Comment by nuclearace** [comment]
@banjun if you want to update the README to include a CocoaPods install section, I'll merge it.

**Pull request merged**
