### PR TITLE
Carthage

### PR DESCRIPTION
**Pull request by nuclearace**

### CODE REVIEW

**Comment by nuclearace** [comment]
Let me know @justinmakaila if this still works.

**Comment by justinmakaila** [comment]
I'll check it out tomorrow



—Justin Makaila

**Comment by nuclearace** [comment]
@justinmakaila Have a chance to look at it?

**Comment by justinmakaila** [comment]
Tons of conflicts and the OS X build fails because it can't find the umbrella header `SocketIO.h`. Did you rename it? Also, what was the motive behind renaming the `SocketIO` directory to `SocketIOClientSwift`?

**Comment by nuclearace** [comment]
I renamed it because it fits more with project name, I would've changed them all but I wanted to keep the fiddling with Xcode to a minimum, but it seems I still messed it up.

**Comment by nuclearace** [comment]
Also what do you mean conflicts?

**Comment by justinmakaila** [comment]
`git` conflicts. I'm gonna run through this in a bit. I may just manage my own fork.

**Pull request closed without merging**
