### PR TITLE
Travis ci test

### PR DESCRIPTION
**Pull request by lightsprint09**

### CODE REVIEW

**Comment by lightsprint09** [comment]
My fault...

**Comment by nuclearace** [comment]
Does travis support Swift?

**Comment by lightsprint09** [comment]
I do not know...
I am currently testing this out. Opened the PR to early.

Sorry for that. Will reopen when done

**Comment by lightsprint09** [comment]
And yes it supports Swift 2, iOS 9 :)

http://blog.travis-ci.com/2015-08-27-xcode-70-beta-for-oss/

**Pull request closed without merging**
