### PR TITLE
Fix crash if error contains formatting strings.

### PR DESCRIPTION
**Pull request by ATLCTO**

### CODE REVIEW

**Comment by nuclearace** [comment]
When does this crash?

**Comment by ATLCTO** [comment]
Our server went down and it crashed the iOS app because % in 100% is a formatting string.

"Got unknown error from server <!DOCTYPE html>\n    <html>\n    <head>\n      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n      <style type=\"text/css\">\n        html, body, iframe { margin: 0; padding: 0; height: 100%; }\n        iframe { display: block; width: 100%; border: none; }\n      </style>\n    <title>Application Error</title>\n    </head>\n    <body>\n      <iframe src=\"//s3.amazonaws.com/heroku_pages/error.html\">\n        <p>Application Error</p>\n      </iframe>\n    </body>\n    </html>"

**Comment by nuclearace** [comment]
Oh I see

**Comment by nuclearace** [comment]
Actually I'm having trouble reproducing. Just calling didError with that string doesn't seem to crash mine.

**Comment by ATLCTO** [comment]
image

**Pull request merged**
