### PR TITLE
v13.0.0

### PR DESCRIPTION
**Pull request by nuclearace**
What's New
========
- Multiplexing namespaces through one engine.
- Adds `.sentPing` and `.gotPong` client events for tracking ping/pongs.
- watchOS support.

Breaking Changes
===========
- Huge API changes. See **Add usage doc link**
- Adds `.sentPing` and `.gotPong` client events for tracking ping/pongs.
- Makes the framework a single target.
- Updates Starscream to 3.0

### CODE REVIEW

**Comment by lightsprint09** [comment]
When using development in carthage I get `No available version for github "daltoniam/Starscream" satisfies the requirement: ~> 3.0.2`

**Comment by nuclearace** [comment]
Someone else reported something like that: https://github.com/socketio/socket.io-client-swift/issues/823

**Comment by nuclearace** [comment]
And that's the wrong issue

**Comment by lightsprint09** [comment]
Is it correct to declare a requirement with minor version number?

**Comment by nuclearace** [comment]
@lightsprint09 For which package manager?

**Comment by lightsprint09** [comment]
Carthage

**Comment by nuclearace** [comment]
I'm not sure. Although thinking about it more I guess it is a little odd to have a patch number.

**Comment by lightsprint09** [comment]
Namespacing seems to be broken...

**Comment by nuclearace** [comment]
@lightsprint09 How so? There's a new API for doing namespaces.

**Comment by lightsprint09** [comment]
I know.
Does v13 supports the old socket.io version?

**Comment by nuclearace** [comment]
@lightsprint09 What do you mean the old socket.io version? It should support 2.0+. 1.0 hasn't been supported since 9 iirc.

**Comment by lightsprint09** [comment]
12 worked fine with 1.0 I guess

**Comment by nuclearace** [comment]
@lightsprint09 What's breaking in the new stuff on 1.0? The major 2.0 change was a change in unicode handling which affected HTTP polling. So you wouldn't really see breaking changes until you started using unicode. And actually 12 is missing one of the changes 2.0 introduced (in 12 the sid is wrong for namespaced sockets)

**Comment by nuclearace** [comment]
https://github.com/socketio/socket.io-client-swift/blob/development/Source/SocketIO/Client/SocketIOClient.swift#L57

**Pull request merged**
