### PR TITLE
add new method engineDidOpen in socketEngineClient protocol

### PR DESCRIPTION
**Pull request by leo0307vb**
Add new method to socketEngineClient to use engine.io without the socket.io

### CODE REVIEW

**Comment by nuclearace** [comment]
Seems a little odd to only put the method call inside the websocket method. It should probably be in SocketEngine.handleOpen somewhere. Since by default socket.io should start by using long-polling and then upgrade to WebSocket

**Comment by nuclearace** [comment]
Also the method should not be optional. And yet do !

**Comment by leo0307vb** [comment]
I updated the call to engineDidOpen and set it not optional

**Comment by nuclearace** [comment]
I think for PR the implementation that the client gives should be empty. Since there's actually another packet that says the socket.io connection is connected

**Pull request merged**
