### PR TITLE
updated parsing to better handle acks

### PR DESCRIPTION
**Pull request by hanishabsigh**

### CODE REVIEW

**Comment by nuclearace** [comment]
This seems kind of redundant. Is something breaking?

**Comment by hanishabsigh** [comment]
Yes, I wasn't receiving an ack for some of my messages because the first regex was outputting some sort of groups. Plus, this seems more efficient.

**Comment by nuclearace** [comment]
I think I'm going to redo parsing

**Comment by nuclearace** [comment]
Since it's basically the same as it's been for months

**Comment by nuclearace** [comment]
Master should handle parsing better

**Pull request closed without merging**
